### ISSUE TITLE
Support images with query strings on them

### ISSUE THREAD

**Issue by benhutton** [imgix/imgix-rb#34] opened 2017-10-11 20:29 UTC
Our image urls already end with a cache busting timestamp for a query string.

Because of https://github.com/imgix/imgix-rb/blob/master/lib/imgix/path.rb#L91, the imgix query string is not being properly appended to an existing query string. It assumes there is no query string. 

Our image paths look something like `/path/to/image.jpg?t=12345567`

Currently, we get something like `/path/to/image.jpg?t=12345567?w=500&h=300`

Too many question marks! It should be `/path/to/image.jpg?t=12345567&w=500&h=300`

**Comment by gregpardo** [comment] 2017-11-21 00:11
We have this same setup with cloudfront. You could probably do something like this... Check if the string contains more than one '?'. If it does replace any following with '&'

**Comment by benhutton** [comment] 2017-11-21 01:27
sure... we are doing that too. Ideally this code would be smart enough that we wouldn't have to though!

**Comment by axelson** [comment] 2018-01-11 00:49
@benhutton what are you doing to work around this? I'm having trouble using a cache busting timestamp

**Comment by benhutton** [comment] 2018-01-11 15:57
@axelson I've moved away from timestamps to asset fingerprinting based based on an md5 hash of the file contents. So, your filename looks like `filename-hash.ext`. Here's an actual URL we're using: https://dg.imgix.net/waiting-for-god-to-text-back-vrcfown9-en/landscape/waiting-for-god-to-text-back-vrcfown9-1d26513c3498499dd96683b1dd770609.jpg

**Comment by axelson** [comment] 2018-01-11 18:57
Ah, ok. That's a bit harder for us since our server never touches the files, they go straight to s3. As far as I can tell it is actually impossible to use query parameters to bust Imgix's cache. At least I only need this as a temporary transition and Imgix's url purging endpoint seems to be working well.

**Comment by sherwinski** [comment] 2019-07-23 18:00
For anyone who might still be wondering about this issue/finding this over a year later, there are a few things I want to mention.
Although this might not have been the case when this issue was originally opened, in this project's latest release you can add the cache busting parameter in the following way:
```rb
client.path("/path/to/image.jpg").to_url({t:12345567})
# .../path/to/image.jpg?ixlib=rb-3.0.0&t=12345567
```
`path()` should only be passed the image path (everything before `?`) while `to_url()` can be used to append any number of query parameters. This would avoid the double `?` scenario, which can cause unexpected behavior on the imgix backend. Again, this behavior might not have always been the case. I also want to note that sometime in the future we will implement better path validation to avoid these types of scenarios. 

Closing this issue now, but feel free to comment back with any questions.

**Closed as completed by sherwinski** 2019-07-23 18:00 UTC
